example_3_fl_auth/app/__init__.py
import logging
import os

from flask import Flask
from flask_login import LoginManager

from pathlib import Path

CONF_FILENAME = "config.py"
CONF_FILEPATH = Path(os.getcwd(), CONF_FILENAME)

# Logging configuration
logging.basicConfig(format="%(asctime)s:%(levelname)s:%(name)s:%(message)s")
logging.getLogger().setLevel(logging.DEBUG)

app = Flask(__name__)
app.config.from_pyfile(CONF_FILEPATH)

with app.app_context():
    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.login_view = 'auth.login'

    from app.auth.views import auth
    from app.common.views import common

    app.register_blueprint(auth)
    app.register_blueprint(common)

    from app.database import init_db

    init_db()

example_3_fl_auth/app/common/views.py
from flask import (
    Blueprint,
    render_template,
)

from flask_login import login_required, current_user

common = Blueprint('common', __name__)


@common.route('/')
@common.route('/home')
def home():
    return render_template('home.html')


@common.route('/user_info')
@login_required
def user_info():
    return f'User info: [{current_user.id}]:{current_user.username}'

example_3_fl_auth/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Authentication</title>
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="{{ url_for('common.home') }}">Home</a>
        </div>
      </div>
    </div>
    <div class="container">
    <br/>
    <div>
      {% for category, message in get_flashed_messages(with_categories=true) %}
        <div class="alert alert-{{category}} alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          {{ message }}
        </div>
      {% endfor %}
      </div>
    {% block container %}{% endblock %}
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    {% block scripts %}
    {% endblock %}
  </body>
</html>

example_3_fl_auth/app/templates/home.html
{% extends 'base.html' %}
 
{% block container %}
  <h1>Welcome</h1>
  {% if current_user.is_authenticated %}
    <h3>Hello, {{ current_user.username }}</h3>
    <a href="{{ url_for('auth.logout') }}">Click here to logout</a>
  {% else %}
  Click here to <a href="{{ url_for('auth.login') }}">login with LDAP</a>
  {% endif %}
{% endblock %}

example_3_fl_auth/app/templates/login.html
{% extends 'home.html' %}
 
{% block container %}
  <div class="top-pad">
    <form
        method="POST"
        action="{{ url_for('auth.login') }}"
        role="form">
      {{ form.csrf_token }}
      <div class="form-group">{{ form.username.label }}: {{ form.username() }}</div>
      <div class="form-group">{{ form.password.label }}: {{ form.password() }}</div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
  </div>
{% endblock %}